- name: check existing stack
  stat:
    path: /usr/local/bin/stack
  register: stack

- name: Download stack
  get_url:
    url: https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz
    dest: /tmp/stack-1.7.1-linux-x86_64.tar.gz
    mode: 0660
  when: converter == 1 and not stack.stat.exists
  tags:
     - setup

- name: extract stack
  unarchive:
    src: /tmp/stack-1.7.1-linux-x86_64.tar.gz
    dest: /tmp
    remote_src: yes
    exclude: doc,LICENSE
  when: converter == 1 and not stack.stat.exists
  tags:
     - setup

- name: install stack
  copy:
    src: /tmp/stack-1.7.1-linux-x86_64/stack
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes
  when: converter == 1 and not stack.stat.exists
  tags:
     - setup

- name: support packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no
  with_items:
    - libgmp3-dev
  when: app == 1
  tags:
     - setup

- name: clone pandoc
  git: repo={{ pandoc_repo }} dest="/usr/src/docs-italia-comandi-conversione" version={{ pandoc_branch }} force={{ force }}
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: clone filters
  git: repo={{ pandoc_filters_repo }} dest="/usr/src/docs-italia-pandoc-filters" version={{ pandoc_filters_branch }} force={{ force }}
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: build conversion commands - expect a **long wait** before it's ready
  command: chdir="/usr/src/docs-italia-comandi-conversione" stack build
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: build pandoc_filters
  command: chdir="/usr/src/docs-italia-pandoc-filters" stack build
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: local install conversion commands - expect a **long wait** before it's ready
  command: chdir="/usr/src/docs-italia-comandi-conversione" stack install
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: local install pandoc_filters
  command: chdir="/usr/src/docs-italia-pandoc-filters" stack install
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: remove existing commands
  file:
    path: /usr/local/bin/{{ item }}
    state: absent
  with_items:
    - converti
    - filtro-acronimi
    - filtro-didascalia
    - filtro-quotes
    - filtro-rimuovi-div
    - filtro-stile-liste
    - pandoc
    - pandoc-font-to-style
    - pandoc-to-sphinx
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: local install filters / commands
  copy: dest="/usr/local/bin/{{ item }}" src="/root/.local/bin/{{ item }}" mode=0755 remote_src=yes
  with_items:
    - converti
    - filtro-acronimi
    - filtro-didascalia
    - filtro-quotes
    - filtro-rimuovi-div
    - filtro-stile-liste
    - pandoc
    - pandoc-font-to-style
    - pandoc-to-sphinx
  when: converter == 1
  tags:
     - deploy_pandoc
     - setup

- name: cleanup build files
  file:
    path: /root/.stack
    state: absent
  when: converter == 1 and pandoc_cleanup == 1
  tags:
     - deploy_pandoc
     - setup
