
---
- hosts: hosts
  gather_facts: True
  become: yes

  vars_files:
    - defaults.yml

  roles:
    - { role: update }
    - { role: ansible }
    - { role: web }
    - { role: sql }
    - { role: es }
    - { role: python }
    - { role: certbot }
    - { role: app }
    - { role: converter-filters }
    - { role: docker }
    - { role: backup }
