
- name: java packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no
  with_items:
    - openjdk-8-jre-headless
  when: es == 1
  tags:
     - setup

- name: ES key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present
  when: es == 1
  tags:
     - setup

- name: Add ES repos
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/1.3/debian stable main' state=present
  when: es == 1 and es_legacy
  tags:
     - setup

- name: Add ES repos
  apt_repository: repo='deb http://artifacts.elastic.co/packages/5.x/apt stable main' state=present
  when: es == 1 and not es_legacy
  tags:
     - setup

- name: ES packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no force=yes
  when: es == 1
  with_items:
    - elasticsearch={{ es_version }}
  tags:
     - setup

- name: Check ES plugin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list
  when: es == 1
  register: es_plugins
  tags:
     - setup

- name: Install ES plugin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
  when: es == 1 and 'analysis-icu' not in es_plugins.stdout_lines
  tags:
     - setup

- name: Configure ES - 1
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    state: present
    line: "cluster.name: docsitalia"
  when: es == 1 and es_hosts != 'localhost'
  tags:
     - setup

- name: Configure ES - 2
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    state: present
    line: "network.host: {{ ansible_default_ipv4.address }}"
  when: es == 1 and es_hosts != 'localhost'
  tags:
     - setup

- name: Enable service elasticsearch
  service: name=elasticsearch enabled=yes state=restarted
  when: es == 1
  tags:
     - setup
