rtd_repo: https://github.com/italia/docs.italia.it/
rtd_branch: italia-2.3.13
rtd_home: /home/docs
rtd_user: docs
rtd_db_name: docs_italia
rtd_db_user: docs
rtd_db_host:
rtd_db_pass:
rtd_db_port: 5432
rtd_virtualenv: /home/docs/virtualenv
rtd_root: "{{ rtd_home }}/docs.italia.it"
rtd_italia_root: "{{ rtd_home }}/italia_rtd"
rtd_logs: "{{ rtd_home }}/log"
rtd_app_server: localhost
rtd_default_version: bozza
rtd_default_language: it
nginx_logs: /var/log/rtd/nginx
nginx_user: www-data
rtd_domain: test.docs.local
rtd_baseurl: test.docs.local
rtd_redis_celery: localhost:6379/1
rtd_redis_cache: localhost:6379/0
rtd_redis_stats: localhost:6379/2
rtd_proto: http
DEFAULT_FROM_EMAIL: 'admin@docs.italia.it'
PUBLIC_API_URL: '{{ rtd_proto }}://{{ rtd_baseurl }}'
PUBLIC_DOMAIN: '{{ rtd_domain }}'
MEDIA_URL: '{{ rtd_proto }}://{{ rtd_baseurl }}/media/'
docker_rtd_image: readthedocs/build:2.0
DEBUG: True
DOCKER_ENABLE: True
EMAIL_HOST: smtp.mailgun.org
USE_SMTP: True
