
- name: postgres key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: sql == 1
  tags:
     - setup

- name: Add Postgres repos
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present
  when: sql == 1
  tags:
     - setup

- name: postgres packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no
  with_items:
    - postgresql-{{ postgres_version }}
    - postgresql-contrib-{{ postgres_version }}
    - postgresql-client-{{ postgres_version }}
  when: sql == 1
  tags:
     - setup

- name: enable postgres network
  replace:
    path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regexp: "#listen_addresses = 'localhost'"
    replace: "listen_addresses = '{{ rtd_db_host }}'"
  when: sql == 1 and rtd_db_host != 'localhost'
  tags:
     - setup

- debug: msg="IP {{ rtd_db_host| ipsubnet(24, 0) }}|{{ rtd_db_host }}"

- name: enable postgres network / pg_hba
  lineinfile:
    path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    state: present
    line: "host      all      all      {{ rtd_db_host| ipsubnet(24, 0) }}      md5"
  when: sql == 1 and rtd_db_host != 'localhost'
  tags:
     - setup

- name: systemd enable
  systemd: name="postgresql" state=restarted enabled=True daemon_reload=yes
  when: sql == 1
  tags:
     - setup
