
- name: deadsnakes key
  apt_key: keyserver=keyserver.ubuntu.com id=BA6932366A755776 state=present
  when: python == 1
  tags:
    - setup

- name: Add deadsnakes repos python 3.x
  apt_repository: repo='deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main' state=present
  when: python == 1
  tags:
    - setup

- name: python packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no
  with_items:
    - python{{ python_version }}
    - python{{ python_version }}-dev
    - python{{ python_version }}-venv
    - virtualenv
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - libtiff5-dev
    - libjpeg-dev
    - zlib1g-dev
    - libfreetype6-dev
    - libjpeg-turbo-progs
    - libffi-dev
  when: python == 1
  tags:
     - setup

- name: python venv for python3
  apt: pkg=python{{ python_version }}-venv state=present update_cache=true install_recommends=no
  when: python == 1 and python_version != 2.7
  tags:
     - setup

- name: support packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no
  with_items:
    - git
    - redis-server
    - redis-tools
    - ca-certificates
    - gunicorn
  when: python == 1
  tags:
     - setup
