
- name: update git
  # RTD 3.7+ requires a git version newer than the one in ubuntu 16.04 we use on deployment environments
  apt_repository:
    repo: ppa:git-core/ppa
  when: app == 1
  tags:
    - setup

- name: support packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no state=latest
  with_items:
    - git
    - redis-server
    - redis-tools
    - ca-certificates
    - gunicorn
  when: app == 1
  tags:
    - setup

- name: wait-for-it
  # wait-for-t package is not available on ubuntu 16.04
  get_url:
    url: "https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh"
    dest: "/usr/local/bin/wait-for-it"
    remote_src: yes
    force: "{{ force }}"
    mode: 0755
  when: app == 1
  tags:
     - setup

- name: check deployment group
  user: name={{ rtd_user }} state=present
  when: app == 1 or worker == 1
  tags:
     - setup
     - deploy

- name: check deployment user
  user: name={{ rtd_user }} state=present home={{ rtd_home }} uid=1005 group={{ rtd_user }} shell=/bin/bash
  when: app == 1 or worker == 1
  tags:
     - setup
     - deploy

- name: ensure docs dir structure
  file: path="{{ rtd_home }}" state=directory mode=0755 owner={{ rtd_user }}
  when: app == 1
  tags:
     - setup
     - deploy

- name: add bash_profile for deployment user
  become_user: "{{ rtd_user }}"
  template: src=../templates/project/bash_profile dest="{{ rtd_home }}/.bash_profile"
  when: app == 1 or worker == 1
  tags:
     - setup

- name: ensure directory structure
  file: path="{{ item }}" state=directory mode=0755 owner={{ nginx_user }}
  with_items:
    - "{{ nginx_logs }}"
  when: app == 1
  tags:
     - setup
     - deploy

- name: ensure directory structure
  file: path="{{ rtd_home }}/{{ item }}" state=directory mode=0755 owner={{ rtd_user }}
  with_items:
    - log
  when: app == 1
  tags:
     - setup
     - deploy

- name: check postgres user
  become_user: "postgres"
  postgresql_user: name={{ rtd_db_user }} password={{ rtd_db_pass }}
  when: sql == 1
  tags:
     - setup
     - deploy

- name: check docs.italia.it db
  become_user: "postgres"
  postgresql_db: name={{ rtd_db_name }} owner={{ rtd_db_user }}
  when: sql == 1
  tags:
     - setup
     - deploy

- name: install rtd
  become_user: "{{ rtd_user }}"
  git: repo={{ rtd_repo }} dest={{ rtd_root }} version={{ rtd_branch }} force={{ force }}
  when: app == 1
  notify:
    - restart rtd gunicorn
    - restart rtd celery
  tags:
     - deploy

- name: copy 404
  become_user: "{{ rtd_user }}"
  copy:
    src: "{{ rtd_root }}/docker/nginx/404"
    dest: "{{ rtd_root }}/media/html/"
    remote_src: yes
  when: app == 1
  tags:
     - deploy

- name: remove legacy virtualenv
  become_user: "{{ rtd_user }}"
  file:
    path: "{{ rtd_virtualenv }}"
    state: absent
  when: app == 1 and upgrade_setup == 1
  tags:
     - deploy

- name: update virtualenv (python 3)
  become_user: "{{ rtd_user }}"
  pip:
    requirements: "{{ rtd_root }}/requirements/docsitalia.txt"
    virtualenv: "{{ rtd_virtualenv }}"
    virtualenv_command: "/usr/bin/python{{ python_version }} -m venv"
  when: app == 1 and python_version != 2.7
  tags:
     - deploy

- name: update virtualenv (python 2.7)
  become_user: "{{ rtd_user }}"
  pip:
    requirements: "{{ rtd_root }}/requirements/docsitalia.txt"
    virtualenv: "{{ rtd_virtualenv }}"
    virtualenv_command: "/usr/bin/virtualenv -p /usr/bin/python{{ python_version }}"
  when: app == 1 and python_version == 2.7
  tags:
     - deploy

- name: install additional requirements in virtualenv
  become_user: "{{ rtd_user }}"
  pip:
    name: "{{ requirements_extra }}"
    virtualenv: "{{ rtd_virtualenv }}"
  when: app == 1
  tags:
     - deploy

- name: install sentry dependency
  become_user: "{{ rtd_user }}"
  pip:
    name: "raven>=6.9"
    virtualenv: "{{ rtd_virtualenv }}"
  when: app == 1 and SENTRY_DSN
  tags:
     - deploy

- name: install converter
  become_user: "{{ rtd_user }}"
  pip:
    name: "{{ converter_app_repo }}@{{ converter_app_branch }}#egg=docs_italia_convertitore_web"
    virtualenv: "{{ rtd_virtualenv }}"
    editable: 1
  when: app == 1 and converter == 1
  tags:
     - deploy

- name: django configuration
  become_user: "{{ rtd_user }}"
  template: src=../templates/project/{{ item }} dest="{{ rtd_root }}/readthedocs/docsitalia/settings/{{ item }}"
  with_items:
    - local_settings.py
  when: app == 1
  tags:
     - deploy
     - settings

- name: run migrations
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py migrate --settings={{ django_settings_module }}"
  environment:
    DOCSITALIA_UPGRADE: "{{ upgrade_setup }}"
  when: app == 1
  tags:
     - deploy

- name: check if slumber api consumer django user exists
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py shell --settings={{ django_settings_module }}"
  args:
    stdin: "from django.contrib.auth.models import User; User.objects.filter(username='{{ SLUMBER_USERNAME }}').exists()"
  register: build_user_available
  ignore_errors: yes
  when: app == 1
  tags:
     - deploy

- name: ==UPGRADE-ONLY== force python version on projects
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py shell --settings={{ django_settings_module }}"
  args:
    stdin: "from readthedocs.projects.models import Project; Project.objects.all().update(python_interpreter='python3');"
  when: app == 1 and upgrade_setup == 1
  tags:
     - deploy

- name: add proper permission to slumber api consumer django user
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py shell --settings={{ django_settings_module }}"
  args:
    stdin: "from django.contrib.auth.models import User, Permission; u = User.objects.get(username='{{ SLUMBER_USERNAME }}'); p = Permission.objects.get(codename='view_project', content_type__app_label='projects'); u.user_permissions.add(p); p = Permission.objects.get(codename='view_version', content_type__app_label='builds'); u.user_permissions.add(p);"
  when: app == 1 and False
  tags:
     - deploy

- name: Build documents script
  template:
    src: "../templates/project/build_docs.sh"
    dest: "{{ rtd_build_script }}"
    force: 1
    mode: 0755
  when: app == 1
  tags:
     - deploy

- name: Build es script
  template:
    src: "../templates/project/build_es.sh"
    dest: "{{ rtd_build_es_script }}"
    force: 1
    mode: 0755
  when: app == 1
  tags:
     - deploy

- name: run collectstatic
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py collectstatic -lc --noinput --settings={{ django_settings_module }}"
  when: app == 1
  tags:
     - deploy

- name: ==UPGRADE-ONLY== drop elastic search indices
  become_user: "{{ rtd_user }}"
  command: "{{ rtd_virtualenv }}/bin/python {{ rtd_root }}/manage.py clear_elasticsearch --settings={{ django_settings_module }}"
  ignore_errors: yes
  when: app == 1 and upgrade_setup==1
  tags:
     - deploy
  notify:
     - restart elasticsearch
     - reindex elasticsearch

- name: systemd environment
  template: src=../templates/systemd/{{ item }}  dest="{{ rtd_home}}/{{ item }}" mode=644
  with_items:
    - rtd_environment
  when: app == 1
  tags:
     - configuration
     - deploy

- name: tempfile
  template: src=../templates/systemd/tempfile  dest=/etc/tmpfiles.d/rtd.conf mode=644 force=1
  when: app == 1
  tags:
     - deploy

- name: systemd-tempfile
  command: systemd-tmpfiles --create
  when: app == 1
  tags:
     - configuration
     - deploy

- name: systemd configuration
  template: src=../templates/systemd/{{ item }}  dest=/etc/systemd/system/{{ item }} mode=644 force=1
  with_items: "{{ systemd_rtd_services }}"
  when: app == 1
  tags:
     - configuration
     - deploy

- name: remove legacy systemd configuration
  file: path=/etc/systemd/system/{{ item }} state=absent
  with_items: "{{ systemd_rtd_services_removed }}"
  when: app == 1
  tags:
     - configuration
     - deploy

- name: systemd enable
  systemd: name="{{ item }}" state=restarted enabled=True daemon_reload=yes
  with_items: "{{ systemd_rtd_services }}"
  when: app == 1
  tags:
     - configuration
     - deploy
     - settings
  notify:
     - restart rtd gunicorn
     - restart rtd celery

- name: nginx configuration
  template: src=../templates/nginx/{{ item }}  dest=/etc/nginx/{{ item  }} force=1
  with_items:
    - nginx.conf
    - conf.d/general-configuration.conf
    - sites-available/readthedocs-main.conf
    - snippets/docs-redirects.conf
    - fallback_defaults
    - proxy_defaults
  notify: reload nginx
  when: http == 1
  tags:
     - configuration
     - deploy  # this is only temporary

- name: disable default  virtualhost
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  when: http == 1
  tags:
     - configuration
     - deploy  # this is only temporary

- name: log dir
  file: path="{{ nginx_logs }}" state=directory owner=www-data group=adm
  when: http == 1

- name: enable virtualhost
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  with_items:
    - readthedocs-main.conf
  notify: restart nginx
  when: http == 1
  tags:
     - configuration
     - deploy  # this is only temporary
