- name: Docker key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  when: worker == 1
  tags:
     - setup

- name: Add Docker repos
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present
  when: worker == 1
  tags:
     - setup

- name: docker packages
  apt: pkg={{ item }} state=present update_cache=true install_recommends=no force=1
  when: worker == 1
  with_items:
    - docker-ce={{ docker_version }}
    - aufs-tools
    - cgroupfs-mount
  tags:
     - setup

- name: pin docker version
  command: apt-mark hold docker-ce
  when: worker == 1
  tags:
     - setup

- name: Override systemd configuration
  template: src=docker.service dest=/etc/systemd/system/docker.service mode=0644 force={{ force }}
  when: worker == 1
  tags:
     - setup

- name: Reload systemd configuration
  command: systemctl daemon-reload
  when: worker == 1
  tags:
     - setup

- name: Enable service docker
  service: name=docker enabled=yes state=restarted
  when: worker == 1
  tags:
     - setup

- name: Add 'rtd_user' in the docker group
  user: name={{ rtd_user }} groups=docker append=yes
  when: worker == 1
  tags:
     - setup

- name: Add local checkout directory
  file: path={{ rtd_root }} owner={{ rtd_user }} group={{ rtd_user }} mode=u=rwxs,g=rwxs,o=rwx state=directory
  when: worker == 1 and docker_main_ip != 'localhost'
  tags:
     - setup

- name: pull docker image ... please wait ... it takes a long time
  command: docker pull "{{ docker_rtd_image }}"
  when: docker_pull == 1 and worker == 1
  tags:
     - setup
     - init

